workspace:
  base: /go
  path: src/github.com/lab46/example

pipeline:
  test:
    image: golang:latest
    commands:
      - export GOPATH=/go
      - go get -u github.com/golang/dep/...
      - dep ensure
      - ./GoTest.sh ${DRONE_COMMIT_SHA}