workspace:
  base: /go
  path: src/github.com/lab46/example

pipeline:
  test:
    image: golang:latest
    commands:
      - go get -u github.com/golang/dep/...
      - dep ensure
      - echo ${DRONE_COMMIT_SHA}
      - ./GoTest.sh ${DRONE_COMMIT_SHA}