version: '3'
services:
  postgres:
      image: onjin/alpine-postgres:9.5
      restart: unless-stopped
      ports:
          - "5432:5432"
      environment:
          LC_ALL: C.UTF-8
          POSTGRES_USER: exampleapp
          POSTGRES_PASSWORD: exampleapp

  redis:
      image: sickp/alpine-redis:3.2.2
      restart: unless-stopped
      ports:
          - "6379:6379"