version: '3'
services:
  bookapp:
    build:
      context: ./files
      dockerfile: Dockerfile.bookapp
    ports:
      - "9000:9000"
  
  rentapp:
    build:
      context: ./files
      dockerfile: Dockerfile.bookapp
    ports:
      - "9001:9000"

  postgres:
      image: onjin/alpine-postgres:9.5
      restart: unless-stopped
      ports:
          - "5432:5432"
      environment:
          LC_ALL: C.UTF-8
          POSTGRES_USER: exampleapp
          POSTGRES_PASSWORD: exampleapp

  redis:
      image: sickp/alpine-redis:3.2.2
      restart: unless-stopped
      ports:
          - "6379:6379"
  
  prometheus:
      image: prom/prometheus:v2.1.0
      restart: unless-stopped
      ports:
          - "9090:9090"
      volumes:
          - ./files/prometheus:/etc/prometheus
          # - ./data:/var/lib/prometheus
      command: ["--config.file=/etc/prometheus/prometheus.yaml", "--storage.tsdb.retention=14d"]